### PR TITLE
The Forbidden Lore: Felinids

### PR DESCRIPTION
**Pull request by EOBGames**
Yep, time to open this can of worms.

Adds lore to felinids, including their effect on cloning technology.

### CODE REVIEW

**Comment by Cyberboss** [comment]
@tgstation/loremasters dew it

**Comment by LemonInTheDark** [comment]
They're not dewing it

**Comment by Cyberboss** [comment]
BogusForsakenAsianlion-size_restricted

**Comment by EOBGames** [comment]
I probably should have specified that I was intending to work on this further hence my stalling on merging it.

Guess the cat's out of the bag now though (ha ha).

**Pull request merged**
